package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1



/**
 * Cementprod generated by hbm2java
 */
public class Cementprod  implements java.io.Serializable {


     private CementprodId id;
     private String type;
     private Integer pkgweight;

    public Cementprod() {
    }

	
    public Cementprod(CementprodId id, String type) {
        this.id = id;
        this.type = type;
    }
    public Cementprod(CementprodId id, String type, Integer pkgweight) {
       this.id = id;
       this.type = type;
       this.pkgweight = pkgweight;
    }
   
    public CementprodId getId() {
        return this.id;
    }
    
    public void setId(CementprodId id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Integer getPkgweight() {
        return this.pkgweight;
    }
    
    public void setPkgweight(Integer pkgweight) {
        this.pkgweight = pkgweight;
    }




}


