package com.rdsic.pcm.data.entity;
// Generated Jul 9, 2016 9:47:03 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cementin generated by hbm2java
 */
public class Cementin  implements java.io.Serializable {


     private Integer cid;
     private String projectcode;
     private String name;
     private int quantity;
     private Date proddate;
     private Date expdate;
     private String regnum;
     private String transportmtd;
     private String transporter;
     private String licplate;
     private String receiver;
     private Date rcvdate;
     private int silo;

    public Cementin() {
    }

	
    public Cementin(String projectcode, String name, int quantity, int silo) {
        this.projectcode = projectcode;
        this.name = name;
        this.quantity = quantity;
        this.silo = silo;
    }
    public Cementin(String projectcode, String name, int quantity, Date proddate, Date expdate, String regnum, String transportmtd, String transporter, String licplate, String receiver, Date rcvdate, int silo) {
       this.projectcode = projectcode;
       this.name = name;
       this.quantity = quantity;
       this.proddate = proddate;
       this.expdate = expdate;
       this.regnum = regnum;
       this.transportmtd = transportmtd;
       this.transporter = transporter;
       this.licplate = licplate;
       this.receiver = receiver;
       this.rcvdate = rcvdate;
       this.silo = silo;
    }
   
    public Integer getCid() {
        return this.cid;
    }
    
    public void setCid(Integer cid) {
        this.cid = cid;
    }
    public String getProjectcode() {
        return this.projectcode;
    }
    
    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getProddate() {
        return this.proddate;
    }
    
    public void setProddate(Date proddate) {
        this.proddate = proddate;
    }
    public Date getExpdate() {
        return this.expdate;
    }
    
    public void setExpdate(Date expdate) {
        this.expdate = expdate;
    }
    public String getRegnum() {
        return this.regnum;
    }
    
    public void setRegnum(String regnum) {
        this.regnum = regnum;
    }
    public String getTransportmtd() {
        return this.transportmtd;
    }
    
    public void setTransportmtd(String transportmtd) {
        this.transportmtd = transportmtd;
    }
    public String getTransporter() {
        return this.transporter;
    }
    
    public void setTransporter(String transporter) {
        this.transporter = transporter;
    }
    public String getLicplate() {
        return this.licplate;
    }
    
    public void setLicplate(String licplate) {
        this.licplate = licplate;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public Date getRcvdate() {
        return this.rcvdate;
    }
    
    public void setRcvdate(Date rcvdate) {
        this.rcvdate = rcvdate;
    }
    public int getSilo() {
        return this.silo;
    }
    
    public void setSilo(int silo) {
        this.silo = silo;
    }




}


