package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * CodedefId generated by hbm2java
 */
public class CodedefId  implements java.io.Serializable {


     private String code;
     private String grp;
     private String tag;

    public CodedefId() {
    }

    public CodedefId(String code, String grp, String tag) {
       this.code = code;
       this.grp = grp;
       this.tag = tag;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getGrp() {
        return this.grp;
    }
    
    public void setGrp(String grp) {
        this.grp = grp;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodedefId) ) return false;
		 CodedefId castOther = ( CodedefId ) other; 
         
		 return ( (this.getCode()==castOther.getCode()) || ( this.getCode()!=null && castOther.getCode()!=null && this.getCode().equals(castOther.getCode()) ) )
 && ( (this.getGrp()==castOther.getGrp()) || ( this.getGrp()!=null && castOther.getGrp()!=null && this.getGrp().equals(castOther.getGrp()) ) )
 && ( (this.getTag()==castOther.getTag()) || ( this.getTag()!=null && castOther.getTag()!=null && this.getTag().equals(castOther.getTag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCode() == null ? 0 : this.getCode().hashCode() );
         result = 37 * result + ( getGrp() == null ? 0 : this.getGrp().hashCode() );
         result = 37 * result + ( getTag() == null ? 0 : this.getTag().hashCode() );
         return result;
   }   


}


