package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dmissuetrack generated by hbm2java
 */
public class Dmissuetrack  implements java.io.Serializable {


     private DmissuetrackId id;
     private Date issueend;
     private String issuetype;
     private String reason;
     private String comment;

    public Dmissuetrack() {
    }

	
    public Dmissuetrack(DmissuetrackId id) {
        this.id = id;
    }
    public Dmissuetrack(DmissuetrackId id, Date issueend, String issuetype, String reason, String comment) {
       this.id = id;
       this.issueend = issueend;
       this.issuetype = issuetype;
       this.reason = reason;
       this.comment = comment;
    }
   
    public DmissuetrackId getId() {
        return this.id;
    }
    
    public void setId(DmissuetrackId id) {
        this.id = id;
    }
    public Date getIssueend() {
        return this.issueend;
    }
    
    public void setIssueend(Date issueend) {
        this.issueend = issueend;
    }
    public String getIssuetype() {
        return this.issuetype;
    }
    
    public void setIssuetype(String issuetype) {
        this.issuetype = issuetype;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


