package com.rdsic.pcm.data.entity;
// Generated Jul 21, 2016 12:09:09 PM by Hibernate Tools 4.3.1



/**
 * Drillingmachine generated by hbm2java
 */
public class Drillingmachine  implements java.io.Serializable {


     private Integer dmid;
     private String code;
     private String name;
     private Integer driver1;
     private Integer driver2;
     private String fmid1;
     private String fmid2;
     private Integer mpid;
     private int cutwing;
     private Double alim;
     private Double vlim;

    public Drillingmachine() {
    }

	
    public Drillingmachine(String code, int cutwing) {
        this.code = code;
        this.cutwing = cutwing;
    }
    public Drillingmachine(String code, String name, Integer driver1, Integer driver2, String fmid1, String fmid2, Integer mpid, int cutwing, Double alim, Double vlim) {
       this.code = code;
       this.name = name;
       this.driver1 = driver1;
       this.driver2 = driver2;
       this.fmid1 = fmid1;
       this.fmid2 = fmid2;
       this.mpid = mpid;
       this.cutwing = cutwing;
       this.alim = alim;
       this.vlim = vlim;
    }
   
    public Integer getDmid() {
        return this.dmid;
    }
    
    public void setDmid(Integer dmid) {
        this.dmid = dmid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getDriver1() {
        return this.driver1;
    }
    
    public void setDriver1(Integer driver1) {
        this.driver1 = driver1;
    }
    public Integer getDriver2() {
        return this.driver2;
    }
    
    public void setDriver2(Integer driver2) {
        this.driver2 = driver2;
    }
    public String getFmid1() {
        return this.fmid1;
    }
    
    public void setFmid1(String fmid1) {
        this.fmid1 = fmid1;
    }
    public String getFmid2() {
        return this.fmid2;
    }
    
    public void setFmid2(String fmid2) {
        this.fmid2 = fmid2;
    }
    public Integer getMpid() {
        return this.mpid;
    }
    
    public void setMpid(Integer mpid) {
        this.mpid = mpid;
    }
    public int getCutwing() {
        return this.cutwing;
    }
    
    public void setCutwing(int cutwing) {
        this.cutwing = cutwing;
    }
    public Double getAlim() {
        return this.alim;
    }
    
    public void setAlim(Double alim) {
        this.alim = alim;
    }
    public Double getVlim() {
        return this.vlim;
    }
    
    public void setVlim(Double vlim) {
        this.vlim = vlim;
    }




}


