package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1



/**
 * DrlmonitorId generated by hbm2java
 */
public class DrlmonitorId  implements java.io.Serializable {


     private String drid;
     private int ppid;
     private String mtype;

    public DrlmonitorId() {
    }

    public DrlmonitorId(String drid, int ppid, String mtype) {
       this.drid = drid;
       this.ppid = ppid;
       this.mtype = mtype;
    }
   
    public String getDrid() {
        return this.drid;
    }
    
    public void setDrid(String drid) {
        this.drid = drid;
    }
    public int getPpid() {
        return this.ppid;
    }
    
    public void setPpid(int ppid) {
        this.ppid = ppid;
    }
    public String getMtype() {
        return this.mtype;
    }
    
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DrlmonitorId) ) return false;
		 DrlmonitorId castOther = ( DrlmonitorId ) other; 
         
		 return ( (this.getDrid()==castOther.getDrid()) || ( this.getDrid()!=null && castOther.getDrid()!=null && this.getDrid().equals(castOther.getDrid()) ) )
 && (this.getPpid()==castOther.getPpid())
 && ( (this.getMtype()==castOther.getMtype()) || ( this.getMtype()!=null && castOther.getMtype()!=null && this.getMtype().equals(castOther.getMtype()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDrid() == null ? 0 : this.getDrid().hashCode() );
         result = 37 * result + this.getPpid();
         result = 37 * result + ( getMtype() == null ? 0 : this.getMtype().hashCode() );
         return result;
   }   


}


