package com.rdsic.pcm.data.entity;
// Generated Jul 18, 2016 2:28:00 PM by Hibernate Tools 4.3.1



/**
 * Mixingplant generated by hbm2java
 */
public class Mixingplant  implements java.io.Serializable {


     private Integer mpid;
     private String code;
     private String name;
     private Integer sid1;
     private Integer sid2;
     private Integer sid3;
     private Integer sid4;
     private Integer sid5;

    public Mixingplant() {
    }

	
    public Mixingplant(String code) {
        this.code = code;
    }
    public Mixingplant(String code, String name, Integer sid1, Integer sid2, Integer sid3, Integer sid4, Integer sid5) {
       this.code = code;
       this.name = name;
       this.sid1 = sid1;
       this.sid2 = sid2;
       this.sid3 = sid3;
       this.sid4 = sid4;
       this.sid5 = sid5;
    }
   
    public Integer getMpid() {
        return this.mpid;
    }
    
    public void setMpid(Integer mpid) {
        this.mpid = mpid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getSid1() {
        return this.sid1;
    }
    
    public void setSid1(Integer sid1) {
        this.sid1 = sid1;
    }
    public Integer getSid2() {
        return this.sid2;
    }
    
    public void setSid2(Integer sid2) {
        this.sid2 = sid2;
    }
    public Integer getSid3() {
        return this.sid3;
    }
    
    public void setSid3(Integer sid3) {
        this.sid3 = sid3;
    }
    public Integer getSid4() {
        return this.sid4;
    }
    
    public void setSid4(Integer sid4) {
        this.sid4 = sid4;
    }
    public Integer getSid5() {
        return this.sid5;
    }
    
    public void setSid5(Integer sid5) {
        this.sid5 = sid5;
    }




}


