package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mixingrecord generated by hbm2java
 */
public class Mixingrecord  implements java.io.Serializable {


     private Integer mrid;
     private int mpid;
     private int sid;
     private String worker;
     private Date mstart;
     private Date mfinish;
     private String cementtype;
     private int cementvol;
     private Integer watervol;

    public Mixingrecord() {
    }

	
    public Mixingrecord(int mpid, int sid, String cementtype, int cementvol) {
        this.mpid = mpid;
        this.sid = sid;
        this.cementtype = cementtype;
        this.cementvol = cementvol;
    }
    public Mixingrecord(int mpid, int sid, String worker, Date mstart, Date mfinish, String cementtype, int cementvol, Integer watervol) {
       this.mpid = mpid;
       this.sid = sid;
       this.worker = worker;
       this.mstart = mstart;
       this.mfinish = mfinish;
       this.cementtype = cementtype;
       this.cementvol = cementvol;
       this.watervol = watervol;
    }
   
    public Integer getMrid() {
        return this.mrid;
    }
    
    public void setMrid(Integer mrid) {
        this.mrid = mrid;
    }
    public int getMpid() {
        return this.mpid;
    }
    
    public void setMpid(int mpid) {
        this.mpid = mpid;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getWorker() {
        return this.worker;
    }
    
    public void setWorker(String worker) {
        this.worker = worker;
    }
    public Date getMstart() {
        return this.mstart;
    }
    
    public void setMstart(Date mstart) {
        this.mstart = mstart;
    }
    public Date getMfinish() {
        return this.mfinish;
    }
    
    public void setMfinish(Date mfinish) {
        this.mfinish = mfinish;
    }
    public String getCementtype() {
        return this.cementtype;
    }
    
    public void setCementtype(String cementtype) {
        this.cementtype = cementtype;
    }
    public int getCementvol() {
        return this.cementvol;
    }
    
    public void setCementvol(int cementvol) {
        this.cementvol = cementvol;
    }
    public Integer getWatervol() {
        return this.watervol;
    }
    
    public void setWatervol(Integer watervol) {
        this.watervol = watervol;
    }




}


