package com.rdsic.pcm.data.entity;
// Generated Jul 18, 2016 2:28:00 PM by Hibernate Tools 4.3.1



/**
 * Oprdef generated by hbm2java
 */
public class Oprdef  implements java.io.Serializable {


     private String code;
     private String name;
     private String soapaction;
     private String description;

    public Oprdef() {
    }

	
    public Oprdef(String code) {
        this.code = code;
    }
    public Oprdef(String code, String name, String soapaction, String description) {
       this.code = code;
       this.name = name;
       this.soapaction = soapaction;
       this.description = description;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSoapaction() {
        return this.soapaction;
    }
    
    public void setSoapaction(String soapaction) {
        this.soapaction = soapaction;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


