package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * OprtagId generated by hbm2java
 */
public class OprtagId  implements java.io.Serializable {


     private String oprcode;
     private String tag;

    public OprtagId() {
    }

    public OprtagId(String oprcode, String tag) {
       this.oprcode = oprcode;
       this.tag = tag;
    }
   
    public String getOprcode() {
        return this.oprcode;
    }
    
    public void setOprcode(String oprcode) {
        this.oprcode = oprcode;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OprtagId) ) return false;
		 OprtagId castOther = ( OprtagId ) other; 
         
		 return ( (this.getOprcode()==castOther.getOprcode()) || ( this.getOprcode()!=null && castOther.getOprcode()!=null && this.getOprcode().equals(castOther.getOprcode()) ) )
 && ( (this.getTag()==castOther.getTag()) || ( this.getTag()!=null && castOther.getTag()!=null && this.getTag().equals(castOther.getTag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOprcode() == null ? 0 : this.getOprcode().hashCode() );
         result = 37 * result + ( getTag() == null ? 0 : this.getTag().hashCode() );
         return result;
   }   


}


