package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pcproject generated by hbm2java
 */
public class Pcproject  implements java.io.Serializable {


     private Integer prid;
     private String code;
     private String name;
     private String invname;
     private String implname;
     private String pmname;
     private String address;
     private Date start;
     private Date finish;
     private Date actstart;
     private Date actfinish;
     private Integer npm;
     private Integer npmlim;
     private Double eps;

    public Pcproject() {
    }

	
    public Pcproject(String code, String name, Date start, Date finish) {
        this.code = code;
        this.name = name;
        this.start = start;
        this.finish = finish;
    }
    public Pcproject(String code, String name, String invname, String implname, String pmname, String address, Date start, Date finish, Date actstart, Date actfinish, Integer npm, Integer npmlim, Double eps) {
       this.code = code;
       this.name = name;
       this.invname = invname;
       this.implname = implname;
       this.pmname = pmname;
       this.address = address;
       this.start = start;
       this.finish = finish;
       this.actstart = actstart;
       this.actfinish = actfinish;
       this.npm = npm;
       this.npmlim = npmlim;
       this.eps = eps;
    }
   
    public Integer getPrid() {
        return this.prid;
    }
    
    public void setPrid(Integer prid) {
        this.prid = prid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getInvname() {
        return this.invname;
    }
    
    public void setInvname(String invname) {
        this.invname = invname;
    }
    public String getImplname() {
        return this.implname;
    }
    
    public void setImplname(String implname) {
        this.implname = implname;
    }
    public String getPmname() {
        return this.pmname;
    }
    
    public void setPmname(String pmname) {
        this.pmname = pmname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getFinish() {
        return this.finish;
    }
    
    public void setFinish(Date finish) {
        this.finish = finish;
    }
    public Date getActstart() {
        return this.actstart;
    }
    
    public void setActstart(Date actstart) {
        this.actstart = actstart;
    }
    public Date getActfinish() {
        return this.actfinish;
    }
    
    public void setActfinish(Date actfinish) {
        this.actfinish = actfinish;
    }
    public Integer getNpm() {
        return this.npm;
    }
    
    public void setNpm(Integer npm) {
        this.npm = npm;
    }
    public Integer getNpmlim() {
        return this.npmlim;
    }
    
    public void setNpmlim(Integer npmlim) {
        this.npmlim = npmlim;
    }
    public Double getEps() {
        return this.eps;
    }
    
    public void setEps(Double eps) {
        this.eps = eps;
    }




}


