package com.rdsic.pcm.data.entity;
// Generated Jun 20, 2016 9:33:45 AM by Hibernate Tools 4.3.1



/**
 * PermissionId generated by hbm2java
 */
public class PermissionId  implements java.io.Serializable {


     private String classid;
     private int fid;

    public PermissionId() {
    }

    public PermissionId(String classid, int fid) {
       this.classid = classid;
       this.fid = fid;
    }
   
    public String getClassid() {
        return this.classid;
    }
    
    public void setClassid(String classid) {
        this.classid = classid;
    }
    public int getFid() {
        return this.fid;
    }
    
    public void setFid(int fid) {
        this.fid = fid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermissionId) ) return false;
		 PermissionId castOther = ( PermissionId ) other; 
         
		 return ( (this.getClassid()==castOther.getClassid()) || ( this.getClassid()!=null && castOther.getClassid()!=null && this.getClassid().equals(castOther.getClassid()) ) )
 && (this.getFid()==castOther.getFid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClassid() == null ? 0 : this.getClassid().hashCode() );
         result = 37 * result + this.getFid();
         return result;
   }   


}


