package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pileplan generated by hbm2java
 */
public class Pileplan  implements java.io.Serializable {


     private Integer ppid;
     private int prid;
     private Integer sbid;
     private String code;
     private String ppname;
     private Double x;
     private Double y;
     private Double rx;
     private Double ry;
     private Double vertically;
     private Integer dmid;
     private Integer driver;
     private String team;
     private Integer mpid;
     private Integer sid;
     private String cementtype;
     private Date start;
     private Date end;
     private Date actstart;
     private Date actend;
     private Double rel0;
     private Double rel1;
     private Double rel2;
     private Double rlp;
     private Double rld;
     private Double dspdmax;
     private Double dspdavg;
     private Double uspdmax;
     private Double uspdavg;
     private Double nmin;
     private Double nav;
     private Double rq;
     private Double fq;
     private Double fn;
     private Double fl;
     private Double fs;
     private String status;

    public Pileplan() {
    }

	
    public Pileplan(int prid, String code, String status) {
        this.prid = prid;
        this.code = code;
        this.status = status;
    }
    public Pileplan(int prid, Integer sbid, String code, String ppname, Double x, Double y, Double rx, Double ry, Double vertically, Integer dmid, Integer driver, String team, Integer mpid, Integer sid, String cementtype, Date start, Date end, Date actstart, Date actend, Double rel0, Double rel1, Double rel2, Double rlp, Double rld, Double dspdmax, Double dspdavg, Double uspdmax, Double uspdavg, Double nmin, Double nav, Double rq, Double fq, Double fn, Double fl, Double fs, String status) {
       this.prid = prid;
       this.sbid = sbid;
       this.code = code;
       this.ppname = ppname;
       this.x = x;
       this.y = y;
       this.rx = rx;
       this.ry = ry;
       this.vertically = vertically;
       this.dmid = dmid;
       this.driver = driver;
       this.team = team;
       this.mpid = mpid;
       this.sid = sid;
       this.cementtype = cementtype;
       this.start = start;
       this.end = end;
       this.actstart = actstart;
       this.actend = actend;
       this.rel0 = rel0;
       this.rel1 = rel1;
       this.rel2 = rel2;
       this.rlp = rlp;
       this.rld = rld;
       this.dspdmax = dspdmax;
       this.dspdavg = dspdavg;
       this.uspdmax = uspdmax;
       this.uspdavg = uspdavg;
       this.nmin = nmin;
       this.nav = nav;
       this.rq = rq;
       this.fq = fq;
       this.fn = fn;
       this.fl = fl;
       this.fs = fs;
       this.status = status;
    }
   
    public Integer getPpid() {
        return this.ppid;
    }
    
    public void setPpid(Integer ppid) {
        this.ppid = ppid;
    }
    public int getPrid() {
        return this.prid;
    }
    
    public void setPrid(int prid) {
        this.prid = prid;
    }
    public Integer getSbid() {
        return this.sbid;
    }
    
    public void setSbid(Integer sbid) {
        this.sbid = sbid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getPpname() {
        return this.ppname;
    }
    
    public void setPpname(String ppname) {
        this.ppname = ppname;
    }
    public Double getX() {
        return this.x;
    }
    
    public void setX(Double x) {
        this.x = x;
    }
    public Double getY() {
        return this.y;
    }
    
    public void setY(Double y) {
        this.y = y;
    }
    public Double getRx() {
        return this.rx;
    }
    
    public void setRx(Double rx) {
        this.rx = rx;
    }
    public Double getRy() {
        return this.ry;
    }
    
    public void setRy(Double ry) {
        this.ry = ry;
    }
    public Double getVertically() {
        return this.vertically;
    }
    
    public void setVertically(Double vertically) {
        this.vertically = vertically;
    }
    public Integer getDmid() {
        return this.dmid;
    }
    
    public void setDmid(Integer dmid) {
        this.dmid = dmid;
    }
    public Integer getDriver() {
        return this.driver;
    }
    
    public void setDriver(Integer driver) {
        this.driver = driver;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public Integer getMpid() {
        return this.mpid;
    }
    
    public void setMpid(Integer mpid) {
        this.mpid = mpid;
    }
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getCementtype() {
        return this.cementtype;
    }
    
    public void setCementtype(String cementtype) {
        this.cementtype = cementtype;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public Date getActstart() {
        return this.actstart;
    }
    
    public void setActstart(Date actstart) {
        this.actstart = actstart;
    }
    public Date getActend() {
        return this.actend;
    }
    
    public void setActend(Date actend) {
        this.actend = actend;
    }
    public Double getRel0() {
        return this.rel0;
    }
    
    public void setRel0(Double rel0) {
        this.rel0 = rel0;
    }
    public Double getRel1() {
        return this.rel1;
    }
    
    public void setRel1(Double rel1) {
        this.rel1 = rel1;
    }
    public Double getRel2() {
        return this.rel2;
    }
    
    public void setRel2(Double rel2) {
        this.rel2 = rel2;
    }
    public Double getRlp() {
        return this.rlp;
    }
    
    public void setRlp(Double rlp) {
        this.rlp = rlp;
    }
    public Double getRld() {
        return this.rld;
    }
    
    public void setRld(Double rld) {
        this.rld = rld;
    }
    public Double getDspdmax() {
        return this.dspdmax;
    }
    
    public void setDspdmax(Double dspdmax) {
        this.dspdmax = dspdmax;
    }
    public Double getDspdavg() {
        return this.dspdavg;
    }
    
    public void setDspdavg(Double dspdavg) {
        this.dspdavg = dspdavg;
    }
    public Double getUspdmax() {
        return this.uspdmax;
    }
    
    public void setUspdmax(Double uspdmax) {
        this.uspdmax = uspdmax;
    }
    public Double getUspdavg() {
        return this.uspdavg;
    }
    
    public void setUspdavg(Double uspdavg) {
        this.uspdavg = uspdavg;
    }
    public Double getNmin() {
        return this.nmin;
    }
    
    public void setNmin(Double nmin) {
        this.nmin = nmin;
    }
    public Double getNav() {
        return this.nav;
    }
    
    public void setNav(Double nav) {
        this.nav = nav;
    }
    public Double getRq() {
        return this.rq;
    }
    
    public void setRq(Double rq) {
        this.rq = rq;
    }
    public Double getFq() {
        return this.fq;
    }
    
    public void setFq(Double fq) {
        this.fq = fq;
    }
    public Double getFn() {
        return this.fn;
    }
    
    public void setFn(Double fn) {
        this.fn = fn;
    }
    public Double getFl() {
        return this.fl;
    }
    
    public void setFl(Double fl) {
        this.fl = fl;
    }
    public Double getFs() {
        return this.fs;
    }
    
    public void setFs(Double fs) {
        this.fs = fs;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


