package com.rdsic.pcm.data.entity;
// Generated Dec 21, 2015 11:39:22 AM by Hibernate Tools 4.3.1



/**
 * PileplanId generated by hbm2java
 */
public class PileplanId  implements java.io.Serializable {


     private String pileCode;
     private String projectCode;

    public PileplanId() {
    }

    public PileplanId(String pileCode, String projectCode) {
       this.pileCode = pileCode;
       this.projectCode = projectCode;
    }
   
    public String getPileCode() {
        return this.pileCode;
    }
    
    public void setPileCode(String pileCode) {
        this.pileCode = pileCode;
    }
    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PileplanId) ) return false;
		 PileplanId castOther = ( PileplanId ) other; 
         
		 return ( (this.getPileCode()==castOther.getPileCode()) || ( this.getPileCode()!=null && castOther.getPileCode()!=null && this.getPileCode().equals(castOther.getPileCode()) ) )
 && ( (this.getProjectCode()==castOther.getProjectCode()) || ( this.getProjectCode()!=null && castOther.getProjectCode()!=null && this.getProjectCode().equals(castOther.getProjectCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPileCode() == null ? 0 : this.getPileCode().hashCode() );
         result = 37 * result + ( getProjectCode() == null ? 0 : this.getProjectCode().hashCode() );
         return result;
   }   


}


