package com.rdsic.pcm.data.entity;
// Generated Jul 9, 2016 9:47:03 AM by Hibernate Tools 4.3.1



/**
 * Piledesign generated by hbm2java
 */
public class Piledesign  implements java.io.Serializable {


     private String code;
     private String name;
     private double diameter;
     private double el0;
     private double el1;
     private double el2;
     private Double lp;
     private Double ld;
     private double q;
     private Double qlim;
     private Double qtotal;
     private double n;
     private Double nlim;
     private Double c;
     private Double wc;
     private Double eps;
     private String cadfile;

    public Piledesign() {
    }

	
    public Piledesign(String code, double diameter, double el0, double el1, double el2, double q, double n) {
        this.code = code;
        this.diameter = diameter;
        this.el0 = el0;
        this.el1 = el1;
        this.el2 = el2;
        this.q = q;
        this.n = n;
    }
    public Piledesign(String code, String name, double diameter, double el0, double el1, double el2, Double lp, Double ld, double q, Double qlim, Double qtotal, double n, Double nlim, Double c, Double wc, Double eps, String cadfile) {
       this.code = code;
       this.name = name;
       this.diameter = diameter;
       this.el0 = el0;
       this.el1 = el1;
       this.el2 = el2;
       this.lp = lp;
       this.ld = ld;
       this.q = q;
       this.qlim = qlim;
       this.qtotal = qtotal;
       this.n = n;
       this.nlim = nlim;
       this.c = c;
       this.wc = wc;
       this.eps = eps;
       this.cadfile = cadfile;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getDiameter() {
        return this.diameter;
    }
    
    public void setDiameter(double diameter) {
        this.diameter = diameter;
    }
    public double getEl0() {
        return this.el0;
    }
    
    public void setEl0(double el0) {
        this.el0 = el0;
    }
    public double getEl1() {
        return this.el1;
    }
    
    public void setEl1(double el1) {
        this.el1 = el1;
    }
    public double getEl2() {
        return this.el2;
    }
    
    public void setEl2(double el2) {
        this.el2 = el2;
    }
    public Double getLp() {
        return this.lp;
    }
    
    public void setLp(Double lp) {
        this.lp = lp;
    }
    public Double getLd() {
        return this.ld;
    }
    
    public void setLd(Double ld) {
        this.ld = ld;
    }
    public double getQ() {
        return this.q;
    }
    
    public void setQ(double q) {
        this.q = q;
    }
    public Double getQlim() {
        return this.qlim;
    }
    
    public void setQlim(Double qlim) {
        this.qlim = qlim;
    }
    public Double getQtotal() {
        return this.qtotal;
    }
    
    public void setQtotal(Double qtotal) {
        this.qtotal = qtotal;
    }
    public double getN() {
        return this.n;
    }
    
    public void setN(double n) {
        this.n = n;
    }
    public Double getNlim() {
        return this.nlim;
    }
    
    public void setNlim(Double nlim) {
        this.nlim = nlim;
    }
    public Double getC() {
        return this.c;
    }
    
    public void setC(Double c) {
        this.c = c;
    }
    public Double getWc() {
        return this.wc;
    }
    
    public void setWc(Double wc) {
        this.wc = wc;
    }
    public Double getEps() {
        return this.eps;
    }
    
    public void setEps(Double eps) {
        this.eps = eps;
    }
    public String getCadfile() {
        return this.cadfile;
    }
    
    public void setCadfile(String cadfile) {
        this.cadfile = cadfile;
    }




}


