package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1



/**
 * Reportdef generated by hbm2java
 */
public class Reportdef  implements java.io.Serializable {


     private String code;
     private String description;

    public Reportdef() {
    }

	
    public Reportdef(String code) {
        this.code = code;
    }
    public Reportdef(String code, String description) {
       this.code = code;
       this.description = description;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


