package com.rdsic.pcm.data.entity;
// Generated Jul 21, 2016 12:09:09 PM by Hibernate Tools 4.3.1



/**
 * Reportparam generated by hbm2java
 */
public class Reportparam  implements java.io.Serializable {


     private ReportparamId id;
     private String partype;
     private String format;
     private Integer ord;
     private String description;

    public Reportparam() {
    }

	
    public Reportparam(ReportparamId id) {
        this.id = id;
    }
    public Reportparam(ReportparamId id, String partype, String format, Integer ord, String description) {
       this.id = id;
       this.partype = partype;
       this.format = format;
       this.ord = ord;
       this.description = description;
    }
   
    public ReportparamId getId() {
        return this.id;
    }
    
    public void setId(ReportparamId id) {
        this.id = id;
    }
    public String getPartype() {
        return this.partype;
    }
    
    public void setPartype(String partype) {
        this.partype = partype;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public Integer getOrd() {
        return this.ord;
    }
    
    public void setOrd(Integer ord) {
        this.ord = ord;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


