package com.rdsic.pcm.data.entity;
// Generated Jul 21, 2016 12:09:09 PM by Hibernate Tools 4.3.1



/**
 * Section generated by hbm2java
 */
public class Section  implements java.io.Serializable {


     private Integer sbid;
     private String name;
     private String projectcode;
     private String note;
     private Integer pilecount;

    public Section() {
    }

	
    public Section(String name) {
        this.name = name;
    }
    public Section(String name, String projectcode, String note, Integer pilecount) {
       this.name = name;
       this.projectcode = projectcode;
       this.note = note;
       this.pilecount = pilecount;
    }
   
    public Integer getSbid() {
        return this.sbid;
    }
    
    public void setSbid(Integer sbid) {
        this.sbid = sbid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getProjectcode() {
        return this.projectcode;
    }
    
    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Integer getPilecount() {
        return this.pilecount;
    }
    
    public void setPilecount(Integer pilecount) {
        this.pilecount = pilecount;
    }




}


