package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Silo generated by hbm2java
 */
public class Silo  implements java.io.Serializable {


     private Integer sid;
     private String code;
     private String name;
     private Integer designvol;
     private Integer actualvol;
     private String actualcm;
     private Date lastupdated;

    public Silo() {
    }

	
    public Silo(String code) {
        this.code = code;
    }
    public Silo(String code, String name, Integer designvol, Integer actualvol, String actualcm, Date lastupdated) {
       this.code = code;
       this.name = name;
       this.designvol = designvol;
       this.actualvol = actualvol;
       this.actualcm = actualcm;
       this.lastupdated = lastupdated;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getDesignvol() {
        return this.designvol;
    }
    
    public void setDesignvol(Integer designvol) {
        this.designvol = designvol;
    }
    public Integer getActualvol() {
        return this.actualvol;
    }
    
    public void setActualvol(Integer actualvol) {
        this.actualvol = actualvol;
    }
    public String getActualcm() {
        return this.actualcm;
    }
    
    public void setActualcm(String actualcm) {
        this.actualcm = actualcm;
    }
    public Date getLastupdated() {
        return this.lastupdated;
    }
    
    public void setLastupdated(Date lastupdated) {
        this.lastupdated = lastupdated;
    }




}


