package com.rdsic.pcm.data.entity;
// Generated Jul 21, 2016 12:09:09 PM by Hibernate Tools 4.3.1



/**
 * VDrlmachineinfoId generated by hbm2java
 */
public class VDrlmachineinfoId  implements java.io.Serializable {


     private int dmid;
     private String dmcode;
     private String dmname;
     private String dmflowmeterid;
     private int cutwing;
     private Double alim;
     private Double vlim;
     private int driverid;
     private String drivername;
     private String team;
     private String role;
     private String userid;
     private int mpid;
     private String mpcode;
     private String mpname;
     private int sid;
     private String silocode;
     private String siloname;

    public VDrlmachineinfoId() {
    }

	
    public VDrlmachineinfoId(int dmid, String dmcode, int cutwing, int driverid, int mpid, String mpcode, int sid, String silocode) {
        this.dmid = dmid;
        this.dmcode = dmcode;
        this.cutwing = cutwing;
        this.driverid = driverid;
        this.mpid = mpid;
        this.mpcode = mpcode;
        this.sid = sid;
        this.silocode = silocode;
    }
    public VDrlmachineinfoId(int dmid, String dmcode, String dmname, String dmflowmeterid, int cutwing, Double alim, Double vlim, int driverid, String drivername, String team, String role, String userid, int mpid, String mpcode, String mpname, int sid, String silocode, String siloname) {
       this.dmid = dmid;
       this.dmcode = dmcode;
       this.dmname = dmname;
       this.dmflowmeterid = dmflowmeterid;
       this.cutwing = cutwing;
       this.alim = alim;
       this.vlim = vlim;
       this.driverid = driverid;
       this.drivername = drivername;
       this.team = team;
       this.role = role;
       this.userid = userid;
       this.mpid = mpid;
       this.mpcode = mpcode;
       this.mpname = mpname;
       this.sid = sid;
       this.silocode = silocode;
       this.siloname = siloname;
    }
   
    public int getDmid() {
        return this.dmid;
    }
    
    public void setDmid(int dmid) {
        this.dmid = dmid;
    }
    public String getDmcode() {
        return this.dmcode;
    }
    
    public void setDmcode(String dmcode) {
        this.dmcode = dmcode;
    }
    public String getDmname() {
        return this.dmname;
    }
    
    public void setDmname(String dmname) {
        this.dmname = dmname;
    }
    public String getDmflowmeterid() {
        return this.dmflowmeterid;
    }
    
    public void setDmflowmeterid(String dmflowmeterid) {
        this.dmflowmeterid = dmflowmeterid;
    }
    public int getCutwing() {
        return this.cutwing;
    }
    
    public void setCutwing(int cutwing) {
        this.cutwing = cutwing;
    }
    public Double getAlim() {
        return this.alim;
    }
    
    public void setAlim(Double alim) {
        this.alim = alim;
    }
    public Double getVlim() {
        return this.vlim;
    }
    
    public void setVlim(Double vlim) {
        this.vlim = vlim;
    }
    public int getDriverid() {
        return this.driverid;
    }
    
    public void setDriverid(int driverid) {
        this.driverid = driverid;
    }
    public String getDrivername() {
        return this.drivername;
    }
    
    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }
    public String getTeam() {
        return this.team;
    }
    
    public void setTeam(String team) {
        this.team = team;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public int getMpid() {
        return this.mpid;
    }
    
    public void setMpid(int mpid) {
        this.mpid = mpid;
    }
    public String getMpcode() {
        return this.mpcode;
    }
    
    public void setMpcode(String mpcode) {
        this.mpcode = mpcode;
    }
    public String getMpname() {
        return this.mpname;
    }
    
    public void setMpname(String mpname) {
        this.mpname = mpname;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getSilocode() {
        return this.silocode;
    }
    
    public void setSilocode(String silocode) {
        this.silocode = silocode;
    }
    public String getSiloname() {
        return this.siloname;
    }
    
    public void setSiloname(String siloname) {
        this.siloname = siloname;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VDrlmachineinfoId) ) return false;
		 VDrlmachineinfoId castOther = ( VDrlmachineinfoId ) other; 
         
		 return (this.getDmid()==castOther.getDmid())
 && ( (this.getDmcode()==castOther.getDmcode()) || ( this.getDmcode()!=null && castOther.getDmcode()!=null && this.getDmcode().equals(castOther.getDmcode()) ) )
 && ( (this.getDmname()==castOther.getDmname()) || ( this.getDmname()!=null && castOther.getDmname()!=null && this.getDmname().equals(castOther.getDmname()) ) )
 && ( (this.getDmflowmeterid()==castOther.getDmflowmeterid()) || ( this.getDmflowmeterid()!=null && castOther.getDmflowmeterid()!=null && this.getDmflowmeterid().equals(castOther.getDmflowmeterid()) ) )
 && (this.getCutwing()==castOther.getCutwing())
 && ( (this.getAlim()==castOther.getAlim()) || ( this.getAlim()!=null && castOther.getAlim()!=null && this.getAlim().equals(castOther.getAlim()) ) )
 && ( (this.getVlim()==castOther.getVlim()) || ( this.getVlim()!=null && castOther.getVlim()!=null && this.getVlim().equals(castOther.getVlim()) ) )
 && (this.getDriverid()==castOther.getDriverid())
 && ( (this.getDrivername()==castOther.getDrivername()) || ( this.getDrivername()!=null && castOther.getDrivername()!=null && this.getDrivername().equals(castOther.getDrivername()) ) )
 && ( (this.getTeam()==castOther.getTeam()) || ( this.getTeam()!=null && castOther.getTeam()!=null && this.getTeam().equals(castOther.getTeam()) ) )
 && ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) )
 && ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
 && (this.getMpid()==castOther.getMpid())
 && ( (this.getMpcode()==castOther.getMpcode()) || ( this.getMpcode()!=null && castOther.getMpcode()!=null && this.getMpcode().equals(castOther.getMpcode()) ) )
 && ( (this.getMpname()==castOther.getMpname()) || ( this.getMpname()!=null && castOther.getMpname()!=null && this.getMpname().equals(castOther.getMpname()) ) )
 && (this.getSid()==castOther.getSid())
 && ( (this.getSilocode()==castOther.getSilocode()) || ( this.getSilocode()!=null && castOther.getSilocode()!=null && this.getSilocode().equals(castOther.getSilocode()) ) )
 && ( (this.getSiloname()==castOther.getSiloname()) || ( this.getSiloname()!=null && castOther.getSiloname()!=null && this.getSiloname().equals(castOther.getSiloname()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDmid();
         result = 37 * result + ( getDmcode() == null ? 0 : this.getDmcode().hashCode() );
         result = 37 * result + ( getDmname() == null ? 0 : this.getDmname().hashCode() );
         result = 37 * result + ( getDmflowmeterid() == null ? 0 : this.getDmflowmeterid().hashCode() );
         result = 37 * result + this.getCutwing();
         result = 37 * result + ( getAlim() == null ? 0 : this.getAlim().hashCode() );
         result = 37 * result + ( getVlim() == null ? 0 : this.getVlim().hashCode() );
         result = 37 * result + this.getDriverid();
         result = 37 * result + ( getDrivername() == null ? 0 : this.getDrivername().hashCode() );
         result = 37 * result + ( getTeam() == null ? 0 : this.getTeam().hashCode() );
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
         result = 37 * result + this.getMpid();
         result = 37 * result + ( getMpcode() == null ? 0 : this.getMpcode().hashCode() );
         result = 37 * result + ( getMpname() == null ? 0 : this.getMpname().hashCode() );
         result = 37 * result + this.getSid();
         result = 37 * result + ( getSilocode() == null ? 0 : this.getSilocode().hashCode() );
         result = 37 * result + ( getSiloname() == null ? 0 : this.getSiloname().hashCode() );
         return result;
   }   


}


