package com.rdsic.pcm.data.entity;
// Generated Jul 19, 2016 4:32:10 PM by Hibernate Tools 4.3.1



/**
 * VDrlmachineinfo generated by hbm2java
 */
public class VDrlmachineinfo  implements java.io.Serializable {


     private VDrlmachineinfoId id;

    public VDrlmachineinfo() {
    }

    public VDrlmachineinfo(VDrlmachineinfoId id) {
       this.id = id;
    }
   
    public VDrlmachineinfoId getId() {
        return this.id;
    }
    
    public void setId(VDrlmachineinfoId id) {
        this.id = id;
    }




}


