package com.rdsic.pcm.data.entity;
// Generated Dec 21, 2015 11:39:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Objects;

/**
 * VProjectpileplanId generated by hbm2java
 */
public class VProjectpileplanId implements java.io.Serializable {

    private String projectcode;
    private String projectName;
    private Date projectStart;
    private Date projectEnd;
    private String pilecode;
    private String piletype;
    private Date pileStart;
    private Date pileFinish;
    private Double planx;
    private Double plany;
    private Integer cementuse;
    private Double rx;
    private Double ry;
    private Integer rel0;
    private String section;
    private Integer diameter;
    private Integer length;
    private Integer el0;
    private Integer el1;
    private Integer el2;
    private Integer qperm;
    private Integer qpermlim;
    private Integer qtotal;

    public VProjectpileplanId() {
    }

    public VProjectpileplanId(String projectcode, String pilecode, Date pileStart, Date pileFinish) {
        this.projectcode = projectcode;
        this.pilecode = pilecode;
        this.pileStart = pileStart;
        this.pileFinish = pileFinish;
    }

    public VProjectpileplanId(String projectcode, String projectName, Date projectStart, Date projectEnd, String pilecode, String piletype, Date pileStart, Date pileFinish, Double planx, Double plany, Integer cementuse, Double rx, Double ry, Integer rel0, String section, Integer diameter, Integer length, Integer el0, Integer el1, Integer el2, Integer qperm, Integer qpermlim, Integer qtotal) {
        this.projectcode = projectcode;
        this.projectName = projectName;
        this.projectStart = projectStart;
        this.projectEnd = projectEnd;
        this.pilecode = pilecode;
        this.piletype = piletype;
        this.pileStart = pileStart;
        this.pileFinish = pileFinish;
        this.planx = planx;
        this.plany = plany;
        this.cementuse = cementuse;
        this.rx = rx;
        this.ry = ry;
        this.rel0 = rel0;
        this.section = section;
        this.diameter = diameter;
        this.length = length;
        this.el0 = el0;
        this.el1 = el1;
        this.el2 = el2;
        this.qperm = qperm;
        this.qpermlim = qpermlim;
        this.qtotal = qtotal;
    }

    public String getProjectcode() {
        return this.projectcode;
    }

    public void setProjectcode(String projectcode) {
        this.projectcode = projectcode;
    }

    public String getProjectName() {
        return this.projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Date getProjectStart() {
        return this.projectStart;
    }

    public void setProjectStart(Date projectStart) {
        this.projectStart = projectStart;
    }

    public Date getProjectEnd() {
        return this.projectEnd;
    }

    public void setProjectEnd(Date projectEnd) {
        this.projectEnd = projectEnd;
    }

    public String getPilecode() {
        return this.pilecode;
    }

    public void setPilecode(String pilecode) {
        this.pilecode = pilecode;
    }

    public String getPiletype() {
        return this.piletype;
    }

    public void setPiletype(String piletype) {
        this.piletype = piletype;
    }

    public Date getPileStart() {
        return this.pileStart;
    }

    public void setPileStart(Date pileStart) {
        this.pileStart = pileStart;
    }

    public Date getPileFinish() {
        return this.pileFinish;
    }

    public void setPileFinish(Date pileFinish) {
        this.pileFinish = pileFinish;
    }

    public Double getPlanx() {
        return this.planx;
    }

    public void setPlanx(Double planx) {
        this.planx = planx;
    }

    public Double getPlany() {
        return this.plany;
    }

    public void setPlany(Double plany) {
        this.plany = plany;
    }

    public Integer getCementuse() {
        return this.cementuse;
    }

    public void setCementuse(Integer cementuse) {
        this.cementuse = cementuse;
    }

    public Double getRx() {
        return this.rx;
    }

    public void setRx(Double rx) {
        this.rx = rx;
    }

    public Double getRy() {
        return this.ry;
    }

    public void setRy(Double ry) {
        this.ry = ry;
    }

    public Integer getRel0() {
        return this.rel0;
    }

    public void setRel0(Integer rel0) {
        this.rel0 = rel0;
    }

    public String getSection() {
        return this.section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public Integer getDiameter() {
        return this.diameter;
    }

    public void setDiameter(Integer diameter) {
        this.diameter = diameter;
    }

    public Integer getLength() {
        return this.length;
    }

    public void setLength(Integer length) {
        this.length = length;
    }

    public Integer getEl0() {
        return this.el0;
    }

    public void setEl0(Integer el0) {
        this.el0 = el0;
    }

    public Integer getEl1() {
        return this.el1;
    }

    public void setEl1(Integer el1) {
        this.el1 = el1;
    }

    public Integer getEl2() {
        return this.el2;
    }

    public void setEl2(Integer el2) {
        this.el2 = el2;
    }

    public Integer getQperm() {
        return this.qperm;
    }

    public void setQperm(Integer qperm) {
        this.qperm = qperm;
    }

    public Integer getQpermlim() {
        return this.qpermlim;
    }

    public void setQpermlim(Integer qpermlim) {
        this.qpermlim = qpermlim;
    }

    public Integer getQtotal() {
        return this.qtotal;
    }

    public void setQtotal(Integer qtotal) {
        this.qtotal = qtotal;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VProjectpileplanId)) {
            return false;
        }
        VProjectpileplanId castOther = (VProjectpileplanId) other;

        return ((this.getProjectcode().equals(castOther.getProjectcode())) || (this.getProjectcode() != null && castOther.getProjectcode() != null && this.getProjectcode().equals(castOther.getProjectcode())))
                && ((this.getProjectName().equals(castOther.getProjectName())) || (this.getProjectName() != null && castOther.getProjectName() != null && this.getProjectName().equals(castOther.getProjectName())))
                && ((this.getProjectStart() == castOther.getProjectStart()) || (this.getProjectStart() != null && castOther.getProjectStart() != null && this.getProjectStart().equals(castOther.getProjectStart())))
                && ((this.getProjectEnd() == castOther.getProjectEnd()) || (this.getProjectEnd() != null && castOther.getProjectEnd() != null && this.getProjectEnd().equals(castOther.getProjectEnd())))
                && ((this.getPilecode().equals(castOther.getPilecode())) || (this.getPilecode() != null && castOther.getPilecode() != null && this.getPilecode().equals(castOther.getPilecode())))
                && ((this.getPiletype().equals(castOther.getPiletype())) || (this.getPiletype() != null && castOther.getPiletype() != null && this.getPiletype().equals(castOther.getPiletype())))
                && ((this.getPileStart() == castOther.getPileStart()) || (this.getPileStart() != null && castOther.getPileStart() != null && this.getPileStart().equals(castOther.getPileStart())))
                && ((this.getPileFinish() == castOther.getPileFinish()) || (this.getPileFinish() != null && castOther.getPileFinish() != null && this.getPileFinish().equals(castOther.getPileFinish())))
                && ((Objects.equals(this.getPlanx(), castOther.getPlanx())) || (this.getPlanx() != null && castOther.getPlanx() != null && this.getPlanx().equals(castOther.getPlanx())))
                && ((Objects.equals(this.getPlany(), castOther.getPlany())) || (this.getPlany() != null && castOther.getPlany() != null && this.getPlany().equals(castOther.getPlany())))
                && ((Objects.equals(this.getCementuse(), castOther.getCementuse())) || (this.getCementuse() != null && castOther.getCementuse() != null && this.getCementuse().equals(castOther.getCementuse())))
                && ((Objects.equals(this.getRx(), castOther.getRx())) || (this.getRx() != null && castOther.getRx() != null && this.getRx().equals(castOther.getRx())))
                && ((Objects.equals(this.getRy(), castOther.getRy())) || (this.getRy() != null && castOther.getRy() != null && this.getRy().equals(castOther.getRy())))
                && ((Objects.equals(this.getRel0(), castOther.getRel0())) || (this.getRel0() != null && castOther.getRel0() != null && this.getRel0().equals(castOther.getRel0())))
                && ((this.getSection() == null ? castOther.getSection() == null : this.getSection().equals(castOther.getSection())) || (this.getSection() != null && castOther.getSection() != null && this.getSection().equals(castOther.getSection())))
                && ((Objects.equals(this.getDiameter(), castOther.getDiameter())) || (this.getDiameter() != null && castOther.getDiameter() != null && this.getDiameter().equals(castOther.getDiameter())))
                && ((Objects.equals(this.getLength(), castOther.getLength())) || (this.getLength() != null && castOther.getLength() != null && this.getLength().equals(castOther.getLength())))
                && ((Objects.equals(this.getEl0(), castOther.getEl0())) || (this.getEl0() != null && castOther.getEl0() != null && this.getEl0().equals(castOther.getEl0())))
                && ((Objects.equals(this.getEl1(), castOther.getEl1())) || (this.getEl1() != null && castOther.getEl1() != null && this.getEl1().equals(castOther.getEl1())))
                && ((Objects.equals(this.getEl2(), castOther.getEl2())) || (this.getEl2() != null && castOther.getEl2() != null && this.getEl2().equals(castOther.getEl2())))
                && ((Objects.equals(this.getQperm(), castOther.getQperm())) || (this.getQperm() != null && castOther.getQperm() != null && this.getQperm().equals(castOther.getQperm())))
                && ((Objects.equals(this.getQpermlim(), castOther.getQpermlim())) || (this.getQpermlim() != null && castOther.getQpermlim() != null && this.getQpermlim().equals(castOther.getQpermlim())))
                && ((Objects.equals(this.getQtotal(), castOther.getQtotal())) || (this.getQtotal() != null && castOther.getQtotal() != null && this.getQtotal().equals(castOther.getQtotal())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getProjectcode() == null ? 0 : this.getProjectcode().hashCode());
        result = 37 * result + (getProjectName() == null ? 0 : this.getProjectName().hashCode());
        result = 37 * result + (getProjectStart() == null ? 0 : this.getProjectStart().hashCode());
        result = 37 * result + (getProjectEnd() == null ? 0 : this.getProjectEnd().hashCode());
        result = 37 * result + (getPilecode() == null ? 0 : this.getPilecode().hashCode());
        result = 37 * result + (getPiletype() == null ? 0 : this.getPiletype().hashCode());
        result = 37 * result + (getPileStart() == null ? 0 : this.getPileStart().hashCode());
        result = 37 * result + (getPileFinish() == null ? 0 : this.getPileFinish().hashCode());
        result = 37 * result + (getPlanx() == null ? 0 : this.getPlanx().hashCode());
        result = 37 * result + (getPlany() == null ? 0 : this.getPlany().hashCode());
        result = 37 * result + (getCementuse() == null ? 0 : this.getCementuse().hashCode());
        result = 37 * result + (getRx() == null ? 0 : this.getRx().hashCode());
        result = 37 * result + (getRy() == null ? 0 : this.getRy().hashCode());
        result = 37 * result + (getRel0() == null ? 0 : this.getRel0().hashCode());
        result = 37 * result + (getSection() == null ? 0 : this.getSection().hashCode());
        result = 37 * result + (getDiameter() == null ? 0 : this.getDiameter().hashCode());
        result = 37 * result + (getLength() == null ? 0 : this.getLength().hashCode());
        result = 37 * result + (getEl0() == null ? 0 : this.getEl0().hashCode());
        result = 37 * result + (getEl1() == null ? 0 : this.getEl1().hashCode());
        result = 37 * result + (getEl2() == null ? 0 : this.getEl2().hashCode());
        result = 37 * result + (getQperm() == null ? 0 : this.getQperm().hashCode());
        result = 37 * result + (getQpermlim() == null ? 0 : this.getQpermlim().hashCode());
        result = 37 * result + (getQtotal() == null ? 0 : this.getQtotal().hashCode());
        return result;
    }

}
