package com.rdsic.pcm.data.entity;
// Generated Dec 21, 2015 11:39:22 AM by Hibernate Tools 4.3.1



/**
 * VProjectpileplan generated by hbm2java
 */
public class VProjectpileplan  implements java.io.Serializable {


     private VProjectpileplanId id;

    public VProjectpileplan() {
    }

    public VProjectpileplan(VProjectpileplanId id) {
       this.id = id;
    }
   
    public VProjectpileplanId getId() {
        return this.id;
    }
    
    public void setId(VProjectpileplanId id) {
        this.id = id;
    }




}


