package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * VUserinformation generated by hbm2java
 */
public class VUserinformation  implements java.io.Serializable {


     private VUserinformationId id;

    public VUserinformation() {
    }

    public VUserinformation(VUserinformationId id) {
       this.id = id;
    }
   
    public VUserinformationId getId() {
        return this.id;
    }
    
    public void setId(VUserinformationId id) {
        this.id = id;
    }




}


