package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * VUseractive generated by hbm2java
 */
public class VUseractive  implements java.io.Serializable {


     private VUseractiveId id;

    public VUseractive() {
    }

    public VUseractive(VUseractiveId id) {
       this.id = id;
    }
   
    public VUseractiveId getId() {
        return this.id;
    }
    
    public void setId(VUseractiveId id) {
        this.id = id;
    }




}


