package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VUserinformationId generated by hbm2java
 */
public class VUserinformationId  implements java.io.Serializable {


     private String userId;
     private String firstName;
     private String lastName;
     private String password;
     private Date dateCreate;
     private Date dateExpire;
     private String userClass;
     private Date lastLogin;
     private int loginFailCount;
     private Date lastActive;
     private String token;
     private String status;
     private String classid;
     private String classname;
     private String classstatus;
     private Integer classfailcount;

    public VUserinformationId() {
    }

	
    public VUserinformationId(String userId, String password, String userClass, int loginFailCount, String status) {
        this.userId = userId;
        this.password = password;
        this.userClass = userClass;
        this.loginFailCount = loginFailCount;
        this.status = status;
    }
    public VUserinformationId(String userId, String firstName, String lastName, String password, Date dateCreate, Date dateExpire, String userClass, Date lastLogin, int loginFailCount, Date lastActive, String token, String status, String classid, String classname, String classstatus, Integer classfailcount) {
       this.userId = userId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.dateCreate = dateCreate;
       this.dateExpire = dateExpire;
       this.userClass = userClass;
       this.lastLogin = lastLogin;
       this.loginFailCount = loginFailCount;
       this.lastActive = lastActive;
       this.token = token;
       this.status = status;
       this.classid = classid;
       this.classname = classname;
       this.classstatus = classstatus;
       this.classfailcount = classfailcount;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateCreate() {
        return this.dateCreate;
    }
    
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }
    public Date getDateExpire() {
        return this.dateExpire;
    }
    
    public void setDateExpire(Date dateExpire) {
        this.dateExpire = dateExpire;
    }
    public String getUserClass() {
        return this.userClass;
    }
    
    public void setUserClass(String userClass) {
        this.userClass = userClass;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public int getLoginFailCount() {
        return this.loginFailCount;
    }
    
    public void setLoginFailCount(int loginFailCount) {
        this.loginFailCount = loginFailCount;
    }
    public Date getLastActive() {
        return this.lastActive;
    }
    
    public void setLastActive(Date lastActive) {
        this.lastActive = lastActive;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getClassid() {
        return this.classid;
    }
    
    public void setClassid(String classid) {
        this.classid = classid;
    }
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }
    public String getClassstatus() {
        return this.classstatus;
    }
    
    public void setClassstatus(String classstatus) {
        this.classstatus = classstatus;
    }
    public Integer getClassfailcount() {
        return this.classfailcount;
    }
    
    public void setClassfailcount(Integer classfailcount) {
        this.classfailcount = classfailcount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VUserinformationId) ) return false;
		 VUserinformationId castOther = ( VUserinformationId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getFirstName()==castOther.getFirstName()) || ( this.getFirstName()!=null && castOther.getFirstName()!=null && this.getFirstName().equals(castOther.getFirstName()) ) )
 && ( (this.getLastName()==castOther.getLastName()) || ( this.getLastName()!=null && castOther.getLastName()!=null && this.getLastName().equals(castOther.getLastName()) ) )
 && ( (this.getPassword()==castOther.getPassword()) || ( this.getPassword()!=null && castOther.getPassword()!=null && this.getPassword().equals(castOther.getPassword()) ) )
 && ( (this.getDateCreate()==castOther.getDateCreate()) || ( this.getDateCreate()!=null && castOther.getDateCreate()!=null && this.getDateCreate().equals(castOther.getDateCreate()) ) )
 && ( (this.getDateExpire()==castOther.getDateExpire()) || ( this.getDateExpire()!=null && castOther.getDateExpire()!=null && this.getDateExpire().equals(castOther.getDateExpire()) ) )
 && ( (this.getUserClass()==castOther.getUserClass()) || ( this.getUserClass()!=null && castOther.getUserClass()!=null && this.getUserClass().equals(castOther.getUserClass()) ) )
 && ( (this.getLastLogin()==castOther.getLastLogin()) || ( this.getLastLogin()!=null && castOther.getLastLogin()!=null && this.getLastLogin().equals(castOther.getLastLogin()) ) )
 && (this.getLoginFailCount()==castOther.getLoginFailCount())
 && ( (this.getLastActive()==castOther.getLastActive()) || ( this.getLastActive()!=null && castOther.getLastActive()!=null && this.getLastActive().equals(castOther.getLastActive()) ) )
 && ( (this.getToken()==castOther.getToken()) || ( this.getToken()!=null && castOther.getToken()!=null && this.getToken().equals(castOther.getToken()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getClassid()==castOther.getClassid()) || ( this.getClassid()!=null && castOther.getClassid()!=null && this.getClassid().equals(castOther.getClassid()) ) )
 && ( (this.getClassname()==castOther.getClassname()) || ( this.getClassname()!=null && castOther.getClassname()!=null && this.getClassname().equals(castOther.getClassname()) ) )
 && ( (this.getClassstatus()==castOther.getClassstatus()) || ( this.getClassstatus()!=null && castOther.getClassstatus()!=null && this.getClassstatus().equals(castOther.getClassstatus()) ) )
 && ( (this.getClassfailcount()==castOther.getClassfailcount()) || ( this.getClassfailcount()!=null && castOther.getClassfailcount()!=null && this.getClassfailcount().equals(castOther.getClassfailcount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getFirstName() == null ? 0 : this.getFirstName().hashCode() );
         result = 37 * result + ( getLastName() == null ? 0 : this.getLastName().hashCode() );
         result = 37 * result + ( getPassword() == null ? 0 : this.getPassword().hashCode() );
         result = 37 * result + ( getDateCreate() == null ? 0 : this.getDateCreate().hashCode() );
         result = 37 * result + ( getDateExpire() == null ? 0 : this.getDateExpire().hashCode() );
         result = 37 * result + ( getUserClass() == null ? 0 : this.getUserClass().hashCode() );
         result = 37 * result + ( getLastLogin() == null ? 0 : this.getLastLogin().hashCode() );
         result = 37 * result + this.getLoginFailCount();
         result = 37 * result + ( getLastActive() == null ? 0 : this.getLastActive().hashCode() );
         result = 37 * result + ( getToken() == null ? 0 : this.getToken().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getClassid() == null ? 0 : this.getClassid().hashCode() );
         result = 37 * result + ( getClassname() == null ? 0 : this.getClassname().hashCode() );
         result = 37 * result + ( getClassstatus() == null ? 0 : this.getClassstatus().hashCode() );
         result = 37 * result + ( getClassfailcount() == null ? 0 : this.getClassfailcount().hashCode() );
         return result;
   }   


}


