package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * VUserpermissionId generated by hbm2java
 */
public class VUserpermissionId  implements java.io.Serializable {


     private String userid;
     private String userclass;
     private Integer fid;
     private String address;
     private String type;
     private String operation;

    public VUserpermissionId() {
    }

	
    public VUserpermissionId(String userid, String userclass) {
        this.userid = userid;
        this.userclass = userclass;
    }
    public VUserpermissionId(String userid, String userclass, Integer fid, String address, String type, String operation) {
       this.userid = userid;
       this.userclass = userclass;
       this.fid = fid;
       this.address = address;
       this.type = type;
       this.operation = operation;
    }
   
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getUserclass() {
        return this.userclass;
    }
    
    public void setUserclass(String userclass) {
        this.userclass = userclass;
    }
    public Integer getFid() {
        return this.fid;
    }
    
    public void setFid(Integer fid) {
        this.fid = fid;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VUserpermissionId) ) return false;
		 VUserpermissionId castOther = ( VUserpermissionId ) other; 
         
		 return ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) )
 && ( (this.getUserclass()==castOther.getUserclass()) || ( this.getUserclass()!=null && castOther.getUserclass()!=null && this.getUserclass().equals(castOther.getUserclass()) ) )
 && ( (this.getFid()==castOther.getFid()) || ( this.getFid()!=null && castOther.getFid()!=null && this.getFid().equals(castOther.getFid()) ) )
 && ( (this.getAddress()==castOther.getAddress()) || ( this.getAddress()!=null && castOther.getAddress()!=null && this.getAddress().equals(castOther.getAddress()) ) )
 && ( (this.getType()==castOther.getType()) || ( this.getType()!=null && castOther.getType()!=null && this.getType().equals(castOther.getType()) ) )
 && ( (this.getOperation()==castOther.getOperation()) || ( this.getOperation()!=null && castOther.getOperation()!=null && this.getOperation().equals(castOther.getOperation()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
         result = 37 * result + ( getUserclass() == null ? 0 : this.getUserclass().hashCode() );
         result = 37 * result + ( getFid() == null ? 0 : this.getFid().hashCode() );
         result = 37 * result + ( getAddress() == null ? 0 : this.getAddress().hashCode() );
         result = 37 * result + ( getType() == null ? 0 : this.getType().hashCode() );
         result = 37 * result + ( getOperation() == null ? 0 : this.getOperation().hashCode() );
         return result;
   }   


}


