package com.rdsic.pcm.data.entity;
// Generated Jun 14, 2016 9:17:57 AM by Hibernate Tools 4.3.1



/**
 * VUserpermission generated by hbm2java
 */
public class VUserpermission  implements java.io.Serializable {


     private VUserpermissionId id;

    public VUserpermission() {
    }

    public VUserpermission(VUserpermissionId id) {
       this.id = id;
    }
   
    public VUserpermissionId getId() {
        return this.id;
    }
    
    public void setId(VUserpermissionId id) {
        this.id = id;
    }




}


